site_name: swgoh-comlink
repo_url: https://github.com/swgoh-utils/comlink-python
repo_name: swgoh-utils/comlink-python
docs_dir: docs
site_url: https://swgoh-comlink.github.io/comlink-python

theme:
  name: material
  favicon: img/favicon.png
  #  custom_dir: docs/overrides
  features:
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.share
    - navigation.indexes
    - navigation.prune
    - toc.follow
    - content.tooltips
    - content.code.annotate
    - content.action.edit
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github-alt

  logo: images/logo-minified.svg
  font:
    code: Roboto Mono


plugins:
  - search
  - awesome-pages
  - autorefs
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
  - mkdocstrings:
      #    custom_templates: docs/templates
      enable_inventory: true
      handlers:
        python:
          selection:
            inherited_members: True
            filters:
              - "!^_"
          rendering:
            members_order: source
            show_bases: True
            show_root_toc_entry: False
            group_by_category: True
            heading_level: 3
            show_if_no_docstring: True


markdown_extensions:
  - meta
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/_snippets
      check_paths: True
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 6
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - md_in_html
