site_name: swgoh-comlink
site_description: Python wrapper for swgoh-comlink proxy service
site_url: https://github.com/swgoh-utils/comlink-python

nav:
  - Introduction: 'index.md'
  - Quickstart: 'quickstart.md'
  - API Reference:
      - SwgohComlink: 'swgoh_comlink.md'
      - SwgohComlinkAsync: 'swgoh_comlink_async.md'
      - Utilities: 'utils.md'
      - Exceptions: 'exceptions.md'
      - Environment Variables: 'env_vars.md'
  - Advanced:
      - Overriding Defaults: 'defaults.md'
      - Logging: 'logging.md'
  - Guides:
      - Troubleshooting: 'troubleshooting.md'
  - Compatibility: 'compatibility.md'
  - Community:
      - Reporting Issues: 'issues.md'
      - Contributing: 'contributing.md'
      - Code of Conduct: 'code_of_conduct.md'

repo_name: swgoh-utils/comlink-python
repo_url: https://github.com/swgoh-utils/comlink-python

theme:
  name: 'material'
  custom_dir: 'overrides'
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'brown'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  extra:
    version:
      provider: mike
  markdown_extensions:
    - admonition
    - codehilite:
        css_class: highlight
    - mkdocstrings
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

plugins:
  - search
  - autorefs
  - git-revision-date-localized
  - git-authors
  - mike
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ src ]
          options:
            show_bases: false
            show_labels: true
            heading_level: 3
            inherited_members: false
            group_by_category: true
            show_category_heading: true
            show_root_full_path: false
            show_root_heading: true
            show_root_members_full_path: false
            show_root_toc_entry: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: false
              trim_doctest_flags: false
              docstring_section_style: Spacy
            merge_init_into_class: true
            separate_signature: true
            filters:
              - "!^_"

extra_css:
  - style/style.css
  - style/mkdocstrings.css

