site_name: swgoh-comlink
site_description: Python wrapper for swgoh-comlink proxy service
site_url: https://github.com/swgoh-utils/comlink-python

nav:
  - Home: index.md
  - SwgohComlink: swgoh_comlink.md
  - SwgohComlinkAsync: swgoh_comlink_async.md
  - Utils: utils.md
  - Logging: logging.md

repo_name: swgoh-utils/comlink-python
repo_url: https://github.com/swgoh-utils/comlink-python

theme:
  name: material
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

extra_css:
  - style.css

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ src ]
          options:
            show_bases: false
            heading_level: 3
            inherited_members: true
            group_by_category: false
            show_category_heading: true
            show_object_full_path: false
            show_root_heading: true
            show_root_toc_entry: true
            show_symbol_type_heading: true
            show_symbol_type_toc: false
            docstring_style: google
            docstring_options:
              ignore_init_summary: false
              trim_doctest_flags: false
              docstring_section_style: Spacy
            merge_init_into_class: true
            filters:
              - "!^_"

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
