name: Bug Report
description: Report broken or incorrect behavior.
labels: [ "Bug::Library" ]
title: "[BUG] Your Title Here"

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to fill out this bug report!
        We rely on users to tell us things that we might not find on our own,
        and your help is greatly valued by the team and others contributing.
        If you want real-time support, consider joining our [Discord](https://discord.gg/interactions) instead.

  - type: input
    attributes:
      label: Library Version
      description: Which version of the library you are currently running.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Bug
      description: A simple summary of your bug report
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please give us a step-by-step process of how you were able to produce this.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Results
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Code
      description: A short snippet of code that showcases the bug.
      render: python

  - type: textarea
    attributes:
      label: Traceback
      description: Was there a traceback? If so, please provide it.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: Let's make sure you've properly done due diligence when reporting this issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true
        - label: I have removed my token from display, if visible.
          required: true
        - label: I have attempted to debug this myself, and I believe this issue is with the library
          required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Any other information about the problem.
