name: docs-builder
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs gh-deploy
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEPLOY: True
