# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: swgoh-comlink python package release

on:
  push:
    branches:
      - 1.13.0rc1

jobs:
  build:
    name: "Build release"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup pip cache
        if: runner.os == 'Linux'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Hatch
        run: pipx install hatch
      - name: Build distribution
        run: hatch build
      - name: Get build version
        id: build_version
        run: echo "version=$(hatch version)" >> $GITHUB_OUTPUT
      - name: Send discord success notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Build of swgoh_comlink version ${{ steps.build_version.outputs.version }} completed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Send discord failure notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build of swgoh_comlink version ${{ steps.build_version.outputs.version }} failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
